USE hans;

ALTER TABLE Dozent 
    ADD COLUMN IF NOT EXISTS Strasse VARCHAR(30) NOT NULL,
    ADD COLUMN IF NOT EXISTS Hausnummer VARCHAR(5) NOT NULL,
    ADD COLUMN IF NOT EXISTS PLZ CHAR(5) NOT NULL,
    ADD COLUMN IF NOT EXISTS Ort VARCHAR(30) NOT NULL;