-- @block NOW
SELECT NOW() FROM DUAL;

-- @block STR_TO_DATE
SELECT STR_TO_DATE('12:25 30.05.2023', '%H:%i %d.%m.%Y') FROM DUAL;

-- @block DATE_FORMAT
SELECT DATE_FORMAT(NOW(), '%H:%i %d.%m.%Y') FROM DUAL;

-- @block DATEDIFF
SELECT DATEDIFF('2023-05-30', '2023-03-15') FROM DUAL;